name: Deploy Erick

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar ambiente
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Rodar yarn e buildar
        run: yarn && yarn build
        
      - name: Executando composer install para dependências do Wordpress
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.COMPOSER_TOKEN }}"} }'
        uses: php-actions/composer@v6
        with:
          version: 2
          args: --ignore-platform-reqs

      - name: Copiando arquivos dos plugins para ambiente de testes
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: --no-perms -O --exclude=.git/ --exclude=.env --exclude=node_modules --delete -Prltvz
          path: ./
          remote_path: /home/ec2-user/wp-content/tema
          remote_host: ${{ secrets.MY_SERVER }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.MY_USER_SERVER }}
          remote_key: ${{ secrets.SSH_DEPLOY }}
